version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: video_sns
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

