name: New task
description: For new task assign
title: "[Task]: "
labels: ["task", "triage"]
assignees:
  - Hosi121
body:
  - type: markdown
    attributes:
      value: |
        Fill the form to assign new task!
  - type: textarea
    id: as-is
    attributes:
      label: As Is
      description: What is the current situation?
      placeholder: Describe the current situation
    validations:
      required: true
  - type: textarea
    id: to-be
    attributes:
      label: To Be
      description: What is the desired outcome?
      placeholder: Describe the desired outcome
    validations:
      required: true
  - type: textarea
    id: branch
    attributes:
      label: working branch
      description: Where is the working branch?
      placeholder: Describe the working branch
    validations:
      required: true
  - type: textarea
    id: memo
    attributes:
      label: Memo
      description: Any additional notes or comments?
      placeholder: Add any additional notes or comments